src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * Boolean values for defining post status
     */
    private const PUBLISHED = 1;
    private const DRAFT = 0;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     *
     * @return \App\Entity\Post
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getContent(): ?string
    {
        return $this->content;
    }

    /**
     * @param string $content
     *
     * @return \App\Entity\Post
     */
    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string|null $image
     *
     * @return \App\Entity\Post
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }


    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdateAtValue()
    {
        $this->updated_at = new DateTime();
    }

    /**
     * @param \DateTimeInterface $updated_at
     *
     * @return \App\Entity\Post
     */
    public function setUpdatedAt(DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAtValue()
    {
        $this->created_at = new DateTime();
    }

    /**
     * @param \DateTimeInterface $created_at
     *
     * @return \App\Entity\Post
     */
    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(): void 
    {
        $this->is_published = self::PUBLISHED;
    }

    public function setIsDraft()
    {
        $this->is_published = self::DRAFT;
    }

    /**
     * @return \App\Entity\User|null
     */
    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    /**
     * @param \App\Entity\User|null $created_by
     *
     * @return \App\Entity\Post
     */
    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }

}

src/Controller/Main/BaseController.php
<?php


namespace App\Controller\Main;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * Class BaseController
 *
 * @package App\Controller\Main
 */
class BaseController extends AbstractController
{
	/**
	 * @return array
	 */
	public function renderDefault()
	{
		return [
			'title' => 'Home:'
		];
		
	}
}

src/Controller/Main/CommentController.php
<?php


namespace App\Controller\Main;


use App\Entity\Comment;
use App\Repository\CommentRepositoryInterface;
use App\Repository\PostRepositoryInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


/**
 * Class CommentController
 *
 * @package App\Controller\Main
 */
class CommentController extends BaseController
{
    private $postRepository;
    private $commentRepository;

    /**
     * CommentController constructor.
     *
     * @param \App\Repository\CommentRepositoryInterface $commentRepository
     * @param \App\Repository\PostRepositoryInterface    $postRepository
     */
    public function __construct(
        CommentRepositoryInterface $commentRepository,
        PostRepositoryInterface $postRepository
    ) {
        $this->commentRepository = $commentRepository;
        $this->postRepository = $postRepository;
    }

    /**
     * Create comment via ajax request (post)
     * Returns all last comments that were added later than the registered  one
     *
     * @Route("/comment/create", name="comment_create")
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     */
    public function create(Request $request): JsonResponse
    {
        $data = json_decode($request->getContent());

        $postId = htmlspecialchars($data->post_id);
        $commentContent = htmlspecialchars($data->comment_content);
        $lastCommentId = htmlspecialchars($data->last_comment_id);

        $lastNewComments = '';

        if (empty($commentContent)) {
            return new JsonResponse([]);
        }

        $post = $this->postRepository->getPost($postId);

        $comment = new Comment();
        $comment->setContent($commentContent);
        $comment = $this->commentRepository->createComment($comment, $post);

        $createdAt = $comment->getCreatedAt();

        if ($lastCommentId) {
            $lastNewComments = $this->commentRepository->getAllLatestComments($postId, $lastCommentId);
        }

        //comments_returned_count- the number of comments to be sent for helping to define  whether
        // to json object is iterable or not (on the front-side in js)
        $response = [
            "comments_returned_count" => empty($lastNewComments)
                ? 0 : count($lastNewComments),
            "last_comments"           => empty($lastNewComments)
                ?
                [
                    "id"         => $comment->getId(),
                    "content"    => $comment->getContent(),
                    "created_at" => $createdAt->format('d.m.Y H:i'),
                ] : $lastNewComments,
        ];

        return new JsonResponse($response);
    }

}

src/Controller/Main/HomeController.php
<?php


namespace App\Controller\Main;

use App\Entity\Post;
use App\Repository\CommentRepositoryInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class HomeController
 *
 * @package App\Controller\Main
 */
class HomeController extends BaseController
{
    private $commentRepository;

    /**
     * HomeController constructor.
     *
     * @param \App\Repository\CommentRepositoryInterface $commentRepository
     */
    public function __construct(
        CommentRepositoryInterface $commentRepository
    )
    {
        $this->commentRepository = $commentRepository;
    }

    /**
	 * @Route("/", name="home")
	 */
	public function index()
	{
	    $posts = $this->getDoctrine()->getRepository(Post::class)
            ->findBy([],['id'=>'DESC']);

		$forRender = $this->renderDefault();
        $forRender['title'] = 'Home: all posts';
        $forRender['posts'] = $posts;

		return $this->render('main/index.html.twig', $forRender);
	}
}

src/Controller/Main/PostController.php
<?php


namespace App\Controller\Main;


use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Repository\CommentRepositoryInterface;
use App\Repository\PostRepositoryInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class PostController
 *
 * @package App\Controller\Main
 */
class PostController extends BaseController
{
    private $commentRepository;
    private $entityManager;
    private $postRepository;

    /**
     * PostController constructor.
     *
     * @param \App\Repository\CommentRepositoryInterface $commentRepository
     * @param \Doctrine\ORM\EntityManagerInterface       $entityManager
     * @param \App\Repository\PostRepositoryInterface    $postRepository
     */
    public function __construct(
        CommentRepositoryInterface $commentRepository,
        EntityManagerInterface $entityManager,
        PostRepositoryInterface $postRepository
    ) {
        $this->commentRepository = $commentRepository;
        $this->entityManager = $entityManager;
        $this->postRepository = $postRepository;
    }

    /**
     * @Route("/posts", name="posts")
     */
    public function index()
    {
        $posts = $this->getDoctrine()->getRepository(Post::class)
                      ->findAll();

        $forRender = $this->renderDefault();
        $forRender['title'] = 'Home: all posts';
        $forRender['posts'] = $posts;

        return $this->render('main/index.html.twig', $forRender);

    }

    /**
     * @Route("/posts/{postId}", name="post_show")
     *
     * @param int                                       $postId
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function show(int $postId, Request $request)
    {
        $post = $this->getDoctrine()->getRepository(Post::class)
                     ->find($postId);

        $comment = new Comment();
        $commentsForm = $this->createForm(CommentType::class, $comment);
        $commentsForm->handleRequest($request);

        //just in case if the form request via http method, and not via ajax request
        if ($commentsForm->isSubmitted() && $commentsForm->isValid()) {

            if (empty(($commentsForm->get('content')->getData()))) {
                return $this->redirectToRoute('post_show', ['postId' => $postId]);
            }

            $this->commentRepository->createComment($comment, $post);
            $this->addFlash('success', 'Comment is added!');

            return $this->redirectToRoute('post_show',['postId'=>$postId]);
        }

        $comments = $this->commentRepository->getAllPublishedCommentsBy($postId);

        $forRender = $this->renderDefault();
        $forRender['title'] = 'Post: '.$post->getTitle();
        $forRender['post'] = $post;
        $forRender['comments'] = $comments;
        $forRender['commentForm'] = $commentsForm->createView();

        return $this->render('main/posts/post.html.twig', $forRender);
    }

    /**
     * @Route("search/posts/", name="search_posts")
     *
     * @param \Symfony\Component\HttpFoundation\Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function search(Request $request)
    {
        $query = $request->query->get('q');
        $searchResult = $this->postRepository->searchBy($query);

        $forRender = $this->renderDefault();
        $forRender['title'] = "Search results for: <i>$query</i>";
        $forRender['searchResult'] = $searchResult;

        return $this->render('main/posts/search.html.twig', $forRender);
    }
}

templates/main/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
              integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
              crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('assets/main/css/styles.css') }}">
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="row no-gutters mb-3">
        <div class="col">
            {% block navbar %}
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <a class="navbar-brand" href="{{ path('home') }}">Blog</a>
                    <ul class="navbar-nav ml-auto">
                        {% block menu %}{% endblock %}
                    </ul>

                    <div class="form-inline my-2 my-lg-0">
                        <form action="{{ path('search_posts') }}" method="get">
                            <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search"
                                   aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </div>
                    <div class="form-inline ml-2 my-2 my-lg-0">
                        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                            <a href="{{ path('admin_home') }}" class="btn btn-secondary my-2 my-sm-0"
                               type="submit">Admin panel</a>
                        {% else %}
                            <a href="{{ path('admin_home') }}" class="btn btn-secondary my-2 my-sm-0"
                               type="submit">Login</a>
                        {% endif %}
                    </div>
                </nav>
            {% endblock %}
        </div>
    </div>
    <div class="row no-gutters">
        <div class="col">
            {% block body %}{% endblock %}
        </div>
    </div>
</div>
{% block javascripts %}
{% endblock %}

</body>
</html>

templates/main/index.html.twig
{% extends 'main/base.html.twig' %}
{% block body %}
    <div class="row mb-3">
        <div class="col">
            <h1>
                {{ title }}
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% for post in posts %}


                <div class="card mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{{ asset('uploads/post/') }}{{ post.image }}" class="card-img" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">

                                        <a href="{{ path('post_show', {'postId': post.id}) }}">
                                            {{ post.title }}
                                        </a>
                                </h5>
                                <p class="card-text">
                                    {{ post.content  [:200] | raw}}...
                                </p>
                                <p class="card-text"><small class="text-muted">
                                        {{ post.createdAt | date('d.m.Y H:i') }}
                                    by {{ post.createdBy.email }}</small></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}